import type { NextPage } from 'next'
import Head from 'next/head'
import { ErrorViewer } from '../Components/ErrorViewer'
import { FileUploader } from '../Components/FileUploader'
import { Header } from '../Components/header'
import styles from '../styles/Home.module.css'
import 'antd/dist/antd.css';
import { ItemSelect, SelectItemIE } from '../Components/ItemSelect'
import { useState } from 'react'
import { useRouter } from 'next/router'



const About: NextPage = () => {

  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header></Header>
        <div className={styles.uploader}>
            <div className={styles.h1}>Наша команда</div>
            <div>
                <img src="/images/member1.png"></img>
                <img src="/images/member2.png"></img>
                <img src="/images/member3.png"></img>
                <img src="/images/member4.png"></img>
                <img src="/images/member5.png"></img>
            </div>
            <div>
                <div>Cсылка на репозиторий GitHub:</div>
                <div>https://github.com/orgs/Ai-hack-MAGNUM-OPUS/repositories</div>
                <div>Cсылка на презентацию:</div>
                <div>https://github.com/orgs/Ai-hack-MAGNUM-OPUS/repositories</div>
            </div>
        </div>
      </main>
    </div>
  )
}

export default About
