import type { NextPage } from 'next'
import Head from 'next/head'
import { MyDocViewer } from '../Components/DocViewer'
import { FileUploader } from '../Components/FileUploader'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <FileUploader onResponse={(res)=>console.log(res)}></FileUploader>
      </main>
    </div>
  )
}

export default Home
